In [30]:
from keras.models import Sequential
import numpy as np
model = Sequential()

In [31]:
from keras.layers import Dense, Activation

model.add(Dense(units=64, input_dim=2,kernel_initializer='normal', activation='relu'))
#model.add(Activation('relu'))
model.add(Dense(6, kernel_initializer='normal', activation='relu'))
model.add(Dense(units=1,kernel_initializer='normal'))
#model.add(Activation('softmax'))

In [32]:
x_train=np.zeros((10000,2))
y_train=np.zeros((10000,1))

for i in np.arange(100):
    for j in np.arange(100):
        x_train[i*10+j,0]=i/10.
        x_train[i*10+j,1]=j/10.
        
        y_train[i*10+j]=(i/10.)**2+2*(j/10.)

In [33]:
x_train[0:13,:]

array([[ 0. ,  0. ],
       [ 0. ,  0.1],
       [ 0. ,  0.2],
       [ 0. ,  0.3],
       [ 0. ,  0.4],
       [ 0. ,  0.5],
       [ 0. ,  0.6],
       [ 0. ,  0.7],
       [ 0. ,  0.8],
       [ 0. ,  0.9],
       [ 0.1,  0. ],
       [ 0.1,  0.1],
       [ 0.1,  0.2]])

In [34]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['accuracy'])

In [35]:
# x_train and y_train are Numpy arrays --just like in the Scikit-Learn API.
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
10000/10000 [==============================] - 0s - loss: 192.6027 - acc: 0.3624     
Epoch 2/100
10000/10000 [==============================] - 0s - loss: 13.4276 - acc: 0.8366     
Epoch 3/100
10000/10000 [==============================] - 0s - loss: 9.4395 - acc: 0.8911     
Epoch 4/100
10000/10000 [==============================] - 0s - loss: 6.4319 - acc: 0.8912     
Epoch 5/100
10000/10000 [==============================] - 0s - loss: 4.2290 - acc: 0.8912     
Epoch 6/100
10000/10000 [==============================] - 0s - loss: 2.8608 - acc: 0.8913     
Epoch 7/100
10000/10000 [==============================] - 0s - loss: 2.2068 - acc: 0.8912     
Epoch 8/100
10000/10000 [==============================] - 0s - loss: 1.8804 - acc: 0.8913     
Epoch 9/100
10000/10000 [==============================] - 0s - loss: 1.7189 - acc: 0.8912     
Epoch 10/100
10000/10000 [==============================] - 0s - loss: 1.6502 - acc: 0.8912     
Epoch 11/100
10000/10000 [==========

10000/10000 [==============================] - 0s - loss: 0.0216 - acc: 0.8926     
Epoch 86/100
10000/10000 [==============================] - 0s - loss: 0.0194 - acc: 0.8927     
Epoch 87/100
10000/10000 [==============================] - 0s - loss: 0.0227 - acc: 0.8929     
Epoch 88/100
10000/10000 [==============================] - 0s - loss: 0.0521 - acc: 0.8927     
Epoch 89/100
10000/10000 [==============================] - 0s - loss: 0.0178 - acc: 0.8927     
Epoch 90/100
10000/10000 [==============================] - 0s - loss: 0.0139 - acc: 0.8928     
Epoch 91/100
10000/10000 [==============================] - 0s - loss: 0.0165 - acc: 0.8927     
Epoch 92/100
10000/10000 [==============================] - 0s - loss: 0.0459 - acc: 0.8926     
Epoch 93/100
10000/10000 [==============================] - 0s - loss: 0.0213 - acc: 0.8927     
Epoch 94/100
10000/10000 [==============================] - 0s - loss: 0.0156 - acc: 0.8928     
Epoch 95/100
10000/10000 [=================

In [36]:
x_test=np.array((2,3))
x_test=x_test.reshape((1,2))
x_test

array([[2, 3]])

In [37]:
classes = model.predict(x_test)

In [38]:
classes

array([[ 9.78684998]], dtype=float32)